/* SPDX-FileCopyrightText: 2011-2022 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

/* lapoule.dev build-fork patch: scene-index population (see the header). */

#include "usd_scene_delegate.hh"

#include <pxr/imaging/hdGp/generativeProceduralPluginRegistry.h>
#include <pxr/imaging/hdGp/generativeProceduralResolvingSceneIndex.h>
#include <pxr/usdImaging/usdImaging/sceneIndices.h>

#include "BLI_fileops.h"
#include "BLI_path_utils.hh"
#include "BLI_string.h"

#include "BKE_appdir.hh"
#include "BKE_report.hh"

#include "DEG_depsgraph_query.hh"

#include "WM_api.hh"
#include "WM_types.hh"

#include "usd.hh"
#include "usd_private.hh"

namespace blender {

using namespace blender::io::usd;

namespace io::hydra {

USDSceneDelegate::USDSceneDelegate(pxr::HdRenderIndex *render_index,
                                   pxr::SdfPath const &delegate_id,
                                   const bool use_materialx)
    : render_index_(render_index), delegate_id_(delegate_id), use_materialx(use_materialx)
{
  /* Temporary directory to write any additional files to, like image or VDB files. */
  char unique_name[FILE_MAXFILE];
  SNPRINTF(unique_name, "%p", this);

  char dir_path[FILE_MAX];
  BLI_path_join(
      dir_path, sizeof(dir_path), BKE_tempdir_session(), "usd_scene_delegate", unique_name);
  BLI_dir_create_recursive(dir_path);

  char file_path[FILE_MAX];
  BLI_path_join(file_path, sizeof(file_path), dir_path, "scene.usdc");

  temp_dir_ = dir_path;
  temp_file_ = file_path;
}

USDSceneDelegate::~USDSceneDelegate()
{
  if (terminal_index_) {
    render_index_->RemoveSceneIndex(terminal_index_);
  }
  BLI_delete(temp_dir_.c_str(), true, true);
}

void USDSceneDelegate::populate(Depsgraph *depsgraph)
{
  USDExportParams params;
  params.use_instancing = true;
  params.relative_paths = false;  /* Unnecessary. */
  params.export_textures = false; /* Don't copy all textures, is slow. */
  params.export_subdiv = SubdivExportMode::Tessellate;
  params.evaluation_mode = DEG_get_mode(depsgraph);
  params.generate_preview_surface = !use_materialx;
  params.generate_materialx_network = use_materialx;

  /* NOTE: Since the reports list will be `nullptr` here, reports generated by export code from
   * this call will only be printed to console. */
  wmJobWorkerStatus worker_status = {};
  ReportList worker_reports = {};
  BKE_reports_init(&worker_reports, RPT_PRINT | RPT_STORE);
  worker_status.reports = &worker_reports;
  params.worker_status = &worker_status;

  /* Create clean directory for export. */
  BLI_delete(temp_dir_.c_str(), true, true);
  BLI_dir_create_recursive(temp_dir_.c_str());

  /* Free previous scene index and stage first to save memory. */
  if (terminal_index_) {
    render_index_->RemoveSceneIndex(terminal_index_);
    terminal_index_ = nullptr;
  }
  stage_index_ = nullptr;
  stage_.Reset();

  /* Convert depsgraph to stage + additional file in temp directory. */
  stage_ = io::usd::export_to_stage(params, depsgraph, temp_file_.c_str());

  /* Hydra 2.0: the standard usdImaging scene-index chain (instancing,
   * materials, draw modes), wrapped in the hdGp resolver so generative
   * procedural prims cook — the point of this patch.
   *
   * Ordering is load-bearing: the resolver cooks ONLY on PrimsAdded
   * notices, never on scene queries (its own words, GetPrim). The whole
   * chain must therefore observe the stage index BEFORE population —
   * SetStage/SetTime come last, so their notices flow through the
   * resolver and cook the procedurals. */
  pxr::UsdImagingCreateSceneIndicesInfo info;
  pxr::UsdImagingSceneIndices indices = pxr::UsdImagingCreateSceneIndices(info);
  stage_index_ = indices.stageSceneIndex;

  terminal_index_ = pxr::HdGpGenerativeProceduralResolvingSceneIndex::New(
      indices.finalSceneIndex);
  render_index_->InsertSceneIndex(terminal_index_, delegate_id_);

  stage_index_->SetStage(stage_);
  stage_index_->SetTime(pxr::UsdTimeCode::Default());

  /* tuile-diag: one-shot observability for the generative pipeline. */
  {
    const pxr::SdfPath probe("/proc_direct");
    pxr::HdSceneIndexPrim p = terminal_index_->GetPrim(probe);
    fprintf(stderr,
            "[tuile-diag] %s primType='%s' hasDataSource=%d\n",
            probe.GetText(),
            p.primType.GetText(),
            int(bool(p.dataSource)));
    for (const pxr::SdfPath &c : terminal_index_->GetChildPrimPaths(probe)) {
      fprintf(stderr, "[tuile-diag] child: %s\n", c.GetText());
    }
    for (const pxr::SdfPath &c :
         terminal_index_->GetChildPrimPaths(pxr::SdfPath::AbsoluteRootPath()))
    {
      fprintf(stderr, "[tuile-diag] root child: %s\n", c.GetText());
    }
    pxr::HdGpGenerativeProcedural *gp =
        pxr::HdGpGenerativeProceduralPluginRegistry::GetInstance()
            .ConstructProcedural(pxr::TfToken("TestCube"), probe);
    fprintf(stderr, "[tuile-diag] ConstructProcedural(TestCube) -> %p\n",
            static_cast<void *>(gp));
    delete gp;
  }

  WM_reports_from_reports_move(nullptr, &worker_reports);

  BKE_reports_free(&worker_reports);
}

}  // namespace io::hydra
}  // namespace blender
