// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod tuile {

#[allow(unused_imports, dead_code)]
pub mod pack {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_TEXTURE_FORMAT: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_TEXTURE_FORMAT: i8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_TEXTURE_FORMAT: [TextureFormat; 2] = [
  TextureFormat::None,
  TextureFormat::Png,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct TextureFormat(pub i8);
#[allow(non_upper_case_globals)]
impl TextureFormat {
  pub const None: Self = Self(0);
  pub const Png: Self = Self(1);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::None,
    Self::Png,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::None => Some("None"),
      Self::Png => Some("Png"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for TextureFormat {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for TextureFormat {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for TextureFormat {
    type Output = TextureFormat;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for TextureFormat {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for TextureFormat {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for TextureFormat {}
/// One payload, as a run of LZ4 bytes in the blob region that follows the
/// table.
///
/// Compression and zero-copy do not contradict each other once they are
/// separated: the structure is read in place, and each payload is an
/// independent block decompressed only if something asks for it.
// struct Block, aligned to 8
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Block(pub [u8; 16]);
impl Default for Block { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl ::core::fmt::Debug for Block {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("Block")
      .field("offset", &self.offset())
      .field("stored", &self.stored())
      .field("raw", &self.raw())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Block {}
impl<'a> ::flatbuffers::Follow<'a> for Block {
  type Inner = &'a Block;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a Block>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a Block {
  type Inner = &'a Block;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<Block>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for Block {
    type Output = Block;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const Block as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(8)
    }
}

impl<'a> ::flatbuffers::Verifiable for Block {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Block {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    offset: u64,
    stored: u32,
    raw: u32,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_offset(offset);
    s.set_stored(stored);
    s.set_raw(raw);
    s
  }

  /// From the start of the blob region, not from the start of the file.
  pub fn offset(&self) -> u64 {
    let mut mem = ::core::mem::MaybeUninit::<<u64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_offset(&mut self, x: u64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  /// Bytes on disk.
  pub fn stored(&self) -> u32 {
    let mut mem = ::core::mem::MaybeUninit::<<u32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_stored(&mut self, x: u32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  /// Bytes after decompression. Known in advance, so a reader allocates once.
  pub fn raw(&self) -> u32 {
    let mut mem = ::core::mem::MaybeUninit::<<u32 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[12..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_raw(&mut self, x: u32) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[12..].as_mut_ptr(),
        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

/// The camera one frame was baked for. Twelve doubles, exactly the shape the
/// ABI's `TuileViewState` carries.
///
/// It is here because a render has no frame number to ask with: the host cooks
/// at a timecode and hands the session a camera. So a pack is addressed by the
/// camera it was baked for, and a camera that matches nothing in the pack is
/// the stage and the pack disagreeing — which must be an error, not a guess.
// struct View, aligned to 8
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct View(pub [u8; 96]);
impl Default for View { 
  fn default() -> Self { 
    Self([0; 96])
  }
}
impl ::core::fmt::Debug for View {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    f.debug_struct("View")
      .field("px", &self.px())
      .field("py", &self.py())
      .field("pz", &self.pz())
      .field("dx", &self.dx())
      .field("dy", &self.dy())
      .field("dz", &self.dz())
      .field("ux", &self.ux())
      .field("uy", &self.uy())
      .field("uz", &self.uz())
      .field("vw", &self.vw())
      .field("vh", &self.vh())
      .field("fovy", &self.fovy())
      .finish()
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for View {}
impl<'a> ::flatbuffers::Follow<'a> for View {
  type Inner = &'a View;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { <&'a View>::follow(buf, loc) }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for &'a View {
  type Inner = &'a View;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    unsafe { ::flatbuffers::follow_cast_ref::<View>(buf, loc) }
  }
}
impl<'b> ::flatbuffers::Push for View {
    type Output = View;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = unsafe { ::core::slice::from_raw_parts(self as *const View as *const u8, <Self as ::flatbuffers::Push>::size()) };
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> ::flatbuffers::PushAlignment {
        ::flatbuffers::PushAlignment::new(8)
    }
}

impl<'a> ::flatbuffers::Verifiable for View {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> View {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    px: f64,
    py: f64,
    pz: f64,
    dx: f64,
    dy: f64,
    dz: f64,
    ux: f64,
    uy: f64,
    uz: f64,
    vw: f64,
    vh: f64,
    fovy: f64,
  ) -> Self {
    let mut s = Self([0; 96]);
    s.set_px(px);
    s.set_py(py);
    s.set_pz(pz);
    s.set_dx(dx);
    s.set_dy(dy);
    s.set_dz(dz);
    s.set_ux(ux);
    s.set_uy(uy);
    s.set_uz(uz);
    s.set_vw(vw);
    s.set_vh(vh);
    s.set_fovy(fovy);
    s
  }

  pub fn px(&self) -> f64 {
    let mut mem = ::core::mem::MaybeUninit::<<f64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_px(&mut self, x: f64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn py(&self) -> f64 {
    let mut mem = ::core::mem::MaybeUninit::<<f64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_py(&mut self, x: f64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn pz(&self) -> f64 {
    let mut mem = ::core::mem::MaybeUninit::<<f64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[16..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_pz(&mut self, x: f64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[16..].as_mut_ptr(),
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn dx(&self) -> f64 {
    let mut mem = ::core::mem::MaybeUninit::<<f64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[24..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_dx(&mut self, x: f64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[24..].as_mut_ptr(),
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn dy(&self) -> f64 {
    let mut mem = ::core::mem::MaybeUninit::<<f64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[32..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_dy(&mut self, x: f64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[32..].as_mut_ptr(),
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn dz(&self) -> f64 {
    let mut mem = ::core::mem::MaybeUninit::<<f64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[40..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_dz(&mut self, x: f64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[40..].as_mut_ptr(),
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn ux(&self) -> f64 {
    let mut mem = ::core::mem::MaybeUninit::<<f64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[48..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_ux(&mut self, x: f64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[48..].as_mut_ptr(),
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn uy(&self) -> f64 {
    let mut mem = ::core::mem::MaybeUninit::<<f64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[56..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_uy(&mut self, x: f64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[56..].as_mut_ptr(),
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn uz(&self) -> f64 {
    let mut mem = ::core::mem::MaybeUninit::<<f64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[64..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_uz(&mut self, x: f64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[64..].as_mut_ptr(),
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn vw(&self) -> f64 {
    let mut mem = ::core::mem::MaybeUninit::<<f64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[72..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_vw(&mut self, x: f64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[72..].as_mut_ptr(),
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn vh(&self) -> f64 {
    let mut mem = ::core::mem::MaybeUninit::<<f64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[80..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_vh(&mut self, x: f64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[80..].as_mut_ptr(),
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn fovy(&self) -> f64 {
    let mut mem = ::core::mem::MaybeUninit::<<f64 as ::flatbuffers::EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    ::flatbuffers::EndianScalar::from_little_endian(unsafe {
      ::core::ptr::copy_nonoverlapping(
        self.0[88..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_fovy(&mut self, x: f64) {
    let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      ::core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[88..].as_mut_ptr(),
        ::core::mem::size_of::<<f64 as ::flatbuffers::EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum TileOffset {}
#[derive(Copy, Clone, PartialEq)]

/// One tile, deduplicated across the whole frame range.
///
/// The identity is `(id, drape)`, never `id` alone: a tile keeps its id from
/// one frame to the next but is re-draped as the camera moves, and two
/// drapings of one tile are two different pictures. A tile visible over forty
/// frames at one draping is stored once.
pub struct Tile<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Tile<'a> {
  type Inner = Tile<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Tile<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_DRAPE: ::flatbuffers::VOffsetT = 6;
  pub const VT_ORIGIN_ECEF: ::flatbuffers::VOffsetT = 8;
  pub const VT_VERTEX_COUNT: ::flatbuffers::VOffsetT = 10;
  pub const VT_INDEX_COUNT: ::flatbuffers::VOffsetT = 12;
  pub const VT_BASE_COLOR_FACTOR: ::flatbuffers::VOffsetT = 14;
  pub const VT_POSITIONS: ::flatbuffers::VOffsetT = 16;
  pub const VT_NORMALS: ::flatbuffers::VOffsetT = 18;
  pub const VT_UVS: ::flatbuffers::VOffsetT = 20;
  pub const VT_INDICES: ::flatbuffers::VOffsetT = 22;
  pub const VT_TEXTURE: ::flatbuffers::VOffsetT = 24;
  pub const VT_TEXTURE_FORMAT: ::flatbuffers::VOffsetT = 26;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Tile { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TileArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Tile<'bldr>> {
    let mut builder = TileBuilder::new(_fbb);
    builder.add_drape(args.drape);
    builder.add_id(args.id);
    if let Some(x) = args.texture { builder.add_texture(x); }
    if let Some(x) = args.indices { builder.add_indices(x); }
    if let Some(x) = args.uvs { builder.add_uvs(x); }
    if let Some(x) = args.normals { builder.add_normals(x); }
    if let Some(x) = args.positions { builder.add_positions(x); }
    if let Some(x) = args.base_color_factor { builder.add_base_color_factor(x); }
    builder.add_index_count(args.index_count);
    builder.add_vertex_count(args.vertex_count);
    if let Some(x) = args.origin_ecef { builder.add_origin_ecef(x); }
    builder.add_texture_format(args.texture_format);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Tile::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn drape(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Tile::VT_DRAPE, Some(0)).unwrap()}
  }
  /// ECEF, f64 — positions below are f32 RELATIVE to this. Narrowing that
  /// subtraction is the one thing not to do.
  #[inline]
  pub fn origin_ecef(&self) -> Option<::flatbuffers::Vector<'a, f64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, f64>>>(Tile::VT_ORIGIN_ECEF, None)}
  }
  #[inline]
  pub fn vertex_count(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Tile::VT_VERTEX_COUNT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn index_count(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Tile::VT_INDEX_COUNT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn base_color_factor(&self) -> Option<::flatbuffers::Vector<'a, f32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, f32>>>(Tile::VT_BASE_COLOR_FACTOR, None)}
  }
  #[inline]
  pub fn positions(&self) -> Option<&'a Block> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Block>(Tile::VT_POSITIONS, None)}
  }
  #[inline]
  pub fn normals(&self) -> Option<&'a Block> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Block>(Tile::VT_NORMALS, None)}
  }
  #[inline]
  pub fn uvs(&self) -> Option<&'a Block> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Block>(Tile::VT_UVS, None)}
  }
  #[inline]
  pub fn indices(&self) -> Option<&'a Block> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Block>(Tile::VT_INDICES, None)}
  }
  #[inline]
  pub fn texture(&self) -> Option<&'a Block> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Block>(Tile::VT_TEXTURE, None)}
  }
  #[inline]
  pub fn texture_format(&self) -> TextureFormat {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<TextureFormat>(Tile::VT_TEXTURE_FORMAT, Some(TextureFormat::None)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Tile<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("id", Self::VT_ID, false)?
     .visit_field::<u64>("drape", Self::VT_DRAPE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, f64>>>("origin_ecef", Self::VT_ORIGIN_ECEF, false)?
     .visit_field::<u32>("vertex_count", Self::VT_VERTEX_COUNT, false)?
     .visit_field::<u32>("index_count", Self::VT_INDEX_COUNT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, f32>>>("base_color_factor", Self::VT_BASE_COLOR_FACTOR, false)?
     .visit_field::<Block>("positions", Self::VT_POSITIONS, false)?
     .visit_field::<Block>("normals", Self::VT_NORMALS, false)?
     .visit_field::<Block>("uvs", Self::VT_UVS, false)?
     .visit_field::<Block>("indices", Self::VT_INDICES, false)?
     .visit_field::<Block>("texture", Self::VT_TEXTURE, false)?
     .visit_field::<TextureFormat>("texture_format", Self::VT_TEXTURE_FORMAT, false)?
     .finish();
    Ok(())
  }
}
pub struct TileArgs<'a> {
    pub id: u64,
    pub drape: u64,
    pub origin_ecef: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, f64>>>,
    pub vertex_count: u32,
    pub index_count: u32,
    pub base_color_factor: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, f32>>>,
    pub positions: Option<&'a Block>,
    pub normals: Option<&'a Block>,
    pub uvs: Option<&'a Block>,
    pub indices: Option<&'a Block>,
    pub texture: Option<&'a Block>,
    pub texture_format: TextureFormat,
}
impl<'a> Default for TileArgs<'a> {
  #[inline]
  fn default() -> Self {
    TileArgs {
      id: 0,
      drape: 0,
      origin_ecef: None,
      vertex_count: 0,
      index_count: 0,
      base_color_factor: None,
      positions: None,
      normals: None,
      uvs: None,
      indices: None,
      texture: None,
      texture_format: TextureFormat::None,
    }
  }
}

pub struct TileBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TileBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: u64) {
    self.fbb_.push_slot::<u64>(Tile::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_drape(&mut self, drape: u64) {
    self.fbb_.push_slot::<u64>(Tile::VT_DRAPE, drape, 0);
  }
  #[inline]
  pub fn add_origin_ecef(&mut self, origin_ecef: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Tile::VT_ORIGIN_ECEF, origin_ecef);
  }
  #[inline]
  pub fn add_vertex_count(&mut self, vertex_count: u32) {
    self.fbb_.push_slot::<u32>(Tile::VT_VERTEX_COUNT, vertex_count, 0);
  }
  #[inline]
  pub fn add_index_count(&mut self, index_count: u32) {
    self.fbb_.push_slot::<u32>(Tile::VT_INDEX_COUNT, index_count, 0);
  }
  #[inline]
  pub fn add_base_color_factor(&mut self, base_color_factor: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , f32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Tile::VT_BASE_COLOR_FACTOR, base_color_factor);
  }
  #[inline]
  pub fn add_positions(&mut self, positions: &Block) {
    self.fbb_.push_slot_always::<&Block>(Tile::VT_POSITIONS, positions);
  }
  #[inline]
  pub fn add_normals(&mut self, normals: &Block) {
    self.fbb_.push_slot_always::<&Block>(Tile::VT_NORMALS, normals);
  }
  #[inline]
  pub fn add_uvs(&mut self, uvs: &Block) {
    self.fbb_.push_slot_always::<&Block>(Tile::VT_UVS, uvs);
  }
  #[inline]
  pub fn add_indices(&mut self, indices: &Block) {
    self.fbb_.push_slot_always::<&Block>(Tile::VT_INDICES, indices);
  }
  #[inline]
  pub fn add_texture(&mut self, texture: &Block) {
    self.fbb_.push_slot_always::<&Block>(Tile::VT_TEXTURE, texture);
  }
  #[inline]
  pub fn add_texture_format(&mut self, texture_format: TextureFormat) {
    self.fbb_.push_slot::<TextureFormat>(Tile::VT_TEXTURE_FORMAT, texture_format, TextureFormat::None);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TileBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TileBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Tile<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Tile<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Tile");
      ds.field("id", &self.id());
      ds.field("drape", &self.drape());
      ds.field("origin_ecef", &self.origin_ecef());
      ds.field("vertex_count", &self.vertex_count());
      ds.field("index_count", &self.index_count());
      ds.field("base_color_factor", &self.base_color_factor());
      ds.field("positions", &self.positions());
      ds.field("normals", &self.normals());
      ds.field("uvs", &self.uvs());
      ds.field("indices", &self.indices());
      ds.field("texture", &self.texture());
      ds.field("texture_format", &self.texture_format());
      ds.finish()
  }
}
pub enum FrameOffset {}
#[derive(Copy, Clone, PartialEq)]

/// What one frame selected, as indices into `Pack.tiles`.
pub struct Frame<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Frame<'a> {
  type Inner = Frame<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Frame<'a> {
  pub const VT_FRAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_TILES: ::flatbuffers::VOffsetT = 6;
  pub const VT_VIEW: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Frame { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FrameArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Frame<'bldr>> {
    let mut builder = FrameBuilder::new(_fbb);
    if let Some(x) = args.view { builder.add_view(x); }
    if let Some(x) = args.tiles { builder.add_tiles(x); }
    builder.add_frame(args.frame);
    builder.finish()
  }


  #[inline]
  pub fn frame(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Frame::VT_FRAME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn tiles(&self) -> Option<::flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u32>>>(Frame::VT_TILES, None)}
  }
  #[inline]
  pub fn view(&self) -> Option<&'a View> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<View>(Frame::VT_VIEW, None)}
  }
}

impl ::flatbuffers::Verifiable for Frame<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("frame", Self::VT_FRAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u32>>>("tiles", Self::VT_TILES, false)?
     .visit_field::<View>("view", Self::VT_VIEW, false)?
     .finish();
    Ok(())
  }
}
pub struct FrameArgs<'a> {
    pub frame: u32,
    pub tiles: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u32>>>,
    pub view: Option<&'a View>,
}
impl<'a> Default for FrameArgs<'a> {
  #[inline]
  fn default() -> Self {
    FrameArgs {
      frame: 0,
      tiles: None,
      view: None,
    }
  }
}

pub struct FrameBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FrameBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_frame(&mut self, frame: u32) {
    self.fbb_.push_slot::<u32>(Frame::VT_FRAME, frame, 0);
  }
  #[inline]
  pub fn add_tiles(&mut self, tiles: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Frame::VT_TILES, tiles);
  }
  #[inline]
  pub fn add_view(&mut self, view: &View) {
    self.fbb_.push_slot_always::<&View>(Frame::VT_VIEW, view);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FrameBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FrameBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Frame<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Frame<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Frame");
      ds.field("frame", &self.frame());
      ds.field("tiles", &self.tiles());
      ds.field("view", &self.view());
      ds.finish()
  }
}
pub enum PackOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Pack<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Pack<'a> {
  type Inner = Pack<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Pack<'a> {
  pub const VT_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_SCENE_DIGEST: ::flatbuffers::VOffsetT = 6;
  pub const VT_FIRST_FRAME: ::flatbuffers::VOffsetT = 8;
  pub const VT_LAST_FRAME: ::flatbuffers::VOffsetT = 10;
  pub const VT_RENDER_ORIGIN: ::flatbuffers::VOffsetT = 12;
  pub const VT_BLOB_DIGEST: ::flatbuffers::VOffsetT = 14;
  pub const VT_CULLING: ::flatbuffers::VOffsetT = 16;
  pub const VT_TILES: ::flatbuffers::VOffsetT = 18;
  pub const VT_FRAMES: ::flatbuffers::VOffsetT = 20;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Pack { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PackArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Pack<'bldr>> {
    let mut builder = PackBuilder::new(_fbb);
    builder.add_blob_digest(args.blob_digest);
    if let Some(x) = args.frames { builder.add_frames(x); }
    if let Some(x) = args.tiles { builder.add_tiles(x); }
    if let Some(x) = args.culling { builder.add_culling(x); }
    if let Some(x) = args.render_origin { builder.add_render_origin(x); }
    builder.add_last_frame(args.last_frame);
    builder.add_first_frame(args.first_frame);
    if let Some(x) = args.scene_digest { builder.add_scene_digest(x); }
    builder.add_version(args.version);
    builder.finish()
  }


  /// Bumped when the layout changes in a way an old reader would misread.
  #[inline]
  pub fn version(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Pack::VT_VERSION, Some(0)).unwrap()}
  }
  /// The digest of the scene this is the bake of. A reader that computes a
  /// different one is holding the wrong pack, and must say so rather than
  /// render it.
  #[inline]
  pub fn scene_digest(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Pack::VT_SCENE_DIGEST, None)}
  }
  #[inline]
  pub fn first_frame(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Pack::VT_FIRST_FRAME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn last_frame(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Pack::VT_LAST_FRAME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn render_origin(&self) -> Option<::flatbuffers::Vector<'a, f64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, f64>>>(Pack::VT_RENDER_ORIGIN, None)}
  }
  /// FNV-1a over the whole blob region, taken at write time.
  ///
  /// A pack travels: written on one machine, pushed to R2, pulled onto a pod,
  /// read by sixteen processes. A payload that arrives bent does not
  /// necessarily fail to decompress — it can hand back plausible bytes, and a
  /// renderer then draws slightly wrong ground and reports success. Checked at
  /// open, once, because that is the only moment at which the answer is still
  /// cheap and still actionable.
  #[inline]
  pub fn blob_digest(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Pack::VT_BLOB_DIGEST, Some(0)).unwrap()}
  }
  /// How the selection was culled when this was baked — "full" or "disabled".
  ///
  /// A pack freezes its selection: a hole baked in is a hole for ever, and it
  /// is invisible in the output. This is the admission, carried with the data,
  /// so a pack made under a known-imperfect cull can never pass for a good one.
  #[inline]
  pub fn culling(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Pack::VT_CULLING, None)}
  }
  /// The deduplicated pool, sorted by (id, drape).
  #[inline]
  pub fn tiles(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Tile<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Tile>>>>(Pack::VT_TILES, None)}
  }
  /// One entry per frame in `[first_frame, last_frame]`, in order.
  #[inline]
  pub fn frames(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Frame<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Frame>>>>(Pack::VT_FRAMES, None)}
  }
}

impl ::flatbuffers::Verifiable for Pack<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("version", Self::VT_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("scene_digest", Self::VT_SCENE_DIGEST, false)?
     .visit_field::<u32>("first_frame", Self::VT_FIRST_FRAME, false)?
     .visit_field::<u32>("last_frame", Self::VT_LAST_FRAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, f64>>>("render_origin", Self::VT_RENDER_ORIGIN, false)?
     .visit_field::<u64>("blob_digest", Self::VT_BLOB_DIGEST, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("culling", Self::VT_CULLING, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Tile>>>>("tiles", Self::VT_TILES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Frame>>>>("frames", Self::VT_FRAMES, false)?
     .finish();
    Ok(())
  }
}
pub struct PackArgs<'a> {
    pub version: u32,
    pub scene_digest: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub first_frame: u32,
    pub last_frame: u32,
    pub render_origin: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, f64>>>,
    pub blob_digest: u64,
    pub culling: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub tiles: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Tile<'a>>>>>,
    pub frames: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Frame<'a>>>>>,
}
impl<'a> Default for PackArgs<'a> {
  #[inline]
  fn default() -> Self {
    PackArgs {
      version: 0,
      scene_digest: None,
      first_frame: 0,
      last_frame: 0,
      render_origin: None,
      blob_digest: 0,
      culling: None,
      tiles: None,
      frames: None,
    }
  }
}

pub struct PackBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PackBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_version(&mut self, version: u32) {
    self.fbb_.push_slot::<u32>(Pack::VT_VERSION, version, 0);
  }
  #[inline]
  pub fn add_scene_digest(&mut self, scene_digest: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Pack::VT_SCENE_DIGEST, scene_digest);
  }
  #[inline]
  pub fn add_first_frame(&mut self, first_frame: u32) {
    self.fbb_.push_slot::<u32>(Pack::VT_FIRST_FRAME, first_frame, 0);
  }
  #[inline]
  pub fn add_last_frame(&mut self, last_frame: u32) {
    self.fbb_.push_slot::<u32>(Pack::VT_LAST_FRAME, last_frame, 0);
  }
  #[inline]
  pub fn add_render_origin(&mut self, render_origin: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , f64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Pack::VT_RENDER_ORIGIN, render_origin);
  }
  #[inline]
  pub fn add_blob_digest(&mut self, blob_digest: u64) {
    self.fbb_.push_slot::<u64>(Pack::VT_BLOB_DIGEST, blob_digest, 0);
  }
  #[inline]
  pub fn add_culling(&mut self, culling: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Pack::VT_CULLING, culling);
  }
  #[inline]
  pub fn add_tiles(&mut self, tiles: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Tile<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Pack::VT_TILES, tiles);
  }
  #[inline]
  pub fn add_frames(&mut self, frames: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Frame<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Pack::VT_FRAMES, frames);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PackBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PackBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Pack<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Pack<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Pack");
      ds.field("version", &self.version());
      ds.field("scene_digest", &self.scene_digest());
      ds.field("first_frame", &self.first_frame());
      ds.field("last_frame", &self.last_frame());
      ds.field("render_origin", &self.render_origin());
      ds.field("blob_digest", &self.blob_digest());
      ds.field("culling", &self.culling());
      ds.field("tiles", &self.tiles());
      ds.field("frames", &self.frames());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Pack`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_pack_unchecked`.
pub fn root_as_pack(buf: &[u8]) -> Result<Pack<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Pack>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Pack` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_pack_unchecked`.
pub fn size_prefixed_root_as_pack(buf: &[u8]) -> Result<Pack<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Pack>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Pack` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_pack_unchecked`.
pub fn root_as_pack_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Pack<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Pack<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Pack` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_pack_unchecked`.
pub fn size_prefixed_root_as_pack_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Pack<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Pack<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Pack and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Pack`.
pub unsafe fn root_as_pack_unchecked(buf: &[u8]) -> Pack<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Pack>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Pack and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Pack`.
pub unsafe fn size_prefixed_root_as_pack_unchecked(buf: &[u8]) -> Pack<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Pack>(buf) }
}
pub const PACK_IDENTIFIER: &str = "TUIL";

#[inline]
pub fn pack_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, PACK_IDENTIFIER, false)
}

#[inline]
pub fn pack_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, PACK_IDENTIFIER, true)
}

#[inline]
pub fn finish_pack_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Pack<'a>>) {
  fbb.finish(root, Some(PACK_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_pack_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Pack<'a>>) {
  fbb.finish_size_prefixed(root, Some(PACK_IDENTIFIER));
}
}  // pub mod pack
}  // pub mod tuile

