[package]
name = "tuile-core"
description = "Render-agnostic OGC 3D Tiles engine: parsing, SSE traversal, content decoding, geometry streaming"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
futures-channel = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
glam = { workspace = true }
gltf = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, optional = true }
tuile-b3dm = { version = "0.0.1", path = "../tuile-b3dm" }
url = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { workspace = true, optional = true }

[dev-dependencies]
futures-executor = { workspace = true }
tempfile = { workspace = true }

[features]
default = []
http = ["dep:reqwest"]
tracing = ["dep:tracing"]
