[package]
name = "tuile-wgpu"
description = "Reference wgpu render backend for tuile-core (native + wasm)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bytemuck = { workspace = true }
futures-util = { workspace = true }
glam = { workspace = true }
thiserror = { workspace = true }
tuile-atmosphere = { version = "0.0.1", path = "../tuile-atmosphere" }
tuile-core = { version = "0.0.1", path = "../tuile-core" }
wgpu = { workspace = true }

[dev-dependencies]
futures-executor = { workspace = true }
futures-util = { workspace = true }
glam = { workspace = true }
image = { workspace = true }
pollster = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tuile-atmosphere = { path = "../tuile-atmosphere" }
tuile-core = { path = "../tuile-core" }
url = { workspace = true }
