[package]
name = "wgpu-viewer"
description = "Demo viewer for tuile: winit + tuile-wgpu"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
dotenvy = { workspace = true }
glam = { workspace = true }
pollster = { workspace = true }
tokio = { workspace = true }
tuile-camera = { version = "0.0.1", path = "../../crates/tuile-camera" }
tuile-core = { version = "0.0.1", path = "../../crates/tuile-core" }
tuile-cesium-ion = { version = "0.0.1", path = "../../crates/tuile-cesium-ion" }
tuile-bing = { version = "0.0.1", path = "../../crates/tuile-bing" }
tuile-planetary = { version = "0.0.1", path = "../../crates/tuile-planetary" }
tuile-native-fetchers = { version = "0.0.1", path = "../../crates/tuile-native-fetchers" }
tuile-wgpu = { version = "0.0.1", path = "../../crates/tuile-wgpu" }
wgpu = { workspace = true }
winit = { workspace = true }
